<?php
  include_once("./inc/header.php");
  include_once("./inc/landing.php");
  include_once("./inc/section_01_thingsChange.php");
  include_once("./inc/section_01_thingsChange_mobile.php");
  include_once("./inc/section_02_whatLimits.php");
  include_once("./inc/section_03_strategy.php");
  include_once("./inc/section_04_pieChart.php");
  include_once("./inc/section_05_piePipes.php");
  include_once("./inc/footer_waves.php");
  include_once("./inc/footer.php");
 ?>
